# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UBC Rocket
email: hello@ubcrocket.com
permalink: /blog/:categories/:year/:month/:day/:title
description: UBC Rocket Engineering Design Team Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sbambey.github.io" # the base hostname & protocol for your site
twitter_username: ubcrocket
facebook_username: ubcrocket


# Build settings
markdown: kramdown
